### ISSUE TITLE
leak test data infromation

### ISSUE THREAD

**Issue by libo-huang** [yfzhang114/AdaNPC#2]
It seems to take the groud truth features from all test data.

In your `AdaNPC`, you take all the test data with ground truth labels (e.g., the name with `out` datasets) as the prototypes for inference.
https://github.com/yfzhang114/AdaNPC/blob/c280d6be2b524a895a554a7bb650ae99f5b11eea/unsupervised_adaptation.py#L327-L328

Officially, the condition `and 'out' not in name` should be added to avoid such leakage of test-data information.
https://github.com/yfzhang114/AdaNPC/blob/c280d6be2b524a895a554a7bb650ae99f5b11eea/domainbed/scripts/unsupervised_adaptation.py#L324-L325

**Comment by yfzhang114** [comment]
Thanks for your interest. *out* datasets are a part of source domains, hence the target domain data will not be leaked.
