### ISSUE TITLE
About run error

### ISSUE THREAD

**Issue by GuanchengWan** [yfzhang114/AdaNPC#3]
when i want to exeute the domainbed.scripts.train.py knn algorithm，i get errors as follows：
    self.classifier = MomentumQueue(self.featurizer.n_outputs, self.hparams['queue_size'], self.hparams['temperature'], self.hparams['k'], num_classes)
KeyError: 'queue_size'

so how to fix it? thanks

**Comment by yfzhang114** [comment]
Apologize for the oversight and I have fixed the problem, you can try it again.
