### ISSUE TITLE
Why care about env{test}_out splits

### ISSUE THREAD

**Issue by mynameisissac** [yfzhang114/AdaNPC#4]
When testing with test-time adaptation algorithm in `unsupervised_adaptation.py`, what is the meaning or usage of storing accuracies and get the best accuracy for `env{test}_out` ? As I think `env{test}_in` should be the split for testing, while `env{test}_out` is for test-domain model selection (according to the original DomainBed).
https://github.com/yfzhang114/AdaNPC/blob/007ec44b851caf8c600ee9d1301ef4bae99af7d5/unsupervised_adaptation.py#L408-L415

Btw I think `ent` should be passed instead of `acc` on line 414

**Comment by yfzhang114** [comment]
As you said, in is used for testing, so we store out for the model selection. The ent is not necessary so here we just set it to ACC and do not log the ent value. If you need to print the value of ents (mostly for the DRM baseline), you can set ent_on_test.append(ent),  Maybe I do not understand the problem clearly, so if there is any problem exists, just submitting another question.

**Comment by mynameisissac** [comment]
Ok thanks, so it means how you selected the best hyperparams combination for Ada is actually by `results_on_test` (or the best acc on test printed on line 442) ?
https://github.com/yfzhang114/AdaNPC/blob/007ec44b851caf8c600ee9d1301ef4bae99af7d5/unsupervised_adaptation.py#L442-L443

**Comment by yfzhang114** [comment]
This is used in our ablations and testing and doesn't affect the sweep process.
